[versions]
agp = "8.13.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.2.1"
activityKtx = "1.8.0"
activityKtxVersion = "1.8.0' // Or a more recent stable version"
fragmentKtx = "1.6.2' // Or a more recent stable version"
materialVersion = "1.13.0"
recyclerview = "1.4.0"
appauth = "0.11.1"
okhttp = "4.12.0"
loggingInterceptor = "4.12.0"
retrofit = "2.11.0"
converterMoshi = "2.11.0"
moshi = "1.15.1"
moshiKotlin = "1.15.1"
x_androidxActivityKtx = "1.9.0"
fragmentKtxVersion = "1.8.0"
lifecycleRuntimeKtx = "2.8.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
activity-ktx = { group = "(", name = "activity-ktx", version.ref = "activityKtx" }
xandroidx-activity-ktx = { group = "'androidx.activity", name = "activity-ktx", version.ref = "activityKtxVersion" }
fragment-ktx = { group = "'androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
appauth = { group = "net.openid", name = "appauth", version.ref = "appauth" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "converterMoshi" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiKotlin" }
x_androidx-activity-ktx = { group = "(", name = "activity-ktx", version.ref = "x_androidxActivityKtx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtxVersion" }
lifecycle-runtime-ktx = { group = "(", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

